-- AI 模型管理系统 PostgreSQL 16 完整建表 SQL
-- 说明：
-- 1. 本脚本包含一个最小 enterprise_space 表，若你的系统已有企业/租户表，可删除该表并调整外键。
-- 2. 所有模型管理数据按 enterprise_id 隔离。
-- 3. 默认模型按模型类型分别设置。

BEGIN;

-- =========================
-- 1. 企业空间表（可复用现有表）
-- =========================
CREATE TABLE IF NOT EXISTS public.enterprise_space (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    status      BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE public.enterprise_space IS '企业空间表';
COMMENT ON COLUMN public.enterprise_space.id IS '企业空间ID';
COMMENT ON COLUMN public.enterprise_space.name IS '企业空间名称';
COMMENT ON COLUMN public.enterprise_space.status IS '状态：true启用，false停用';
COMMENT ON COLUMN public.enterprise_space.created_at IS '创建时间';
COMMENT ON COLUMN public.enterprise_space.updated_at IS '更新时间';

-- =========================
-- 2. 公共更新时间函数
-- =========================
CREATE OR REPLACE FUNCTION public.fn_set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at := NOW();
    RETURN NEW;
END;
$$;

-- =========================
-- 3. 已接入厂商配置表
-- =========================
CREATE TABLE IF NOT EXISTS public.ai_model_provider (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enterprise_id     BIGINT NOT NULL,
    provider_code     VARCHAR(50) NOT NULL,
    provider_name     VARCHAR(100) NOT NULL,
    deployment_type   VARCHAR(20) NOT NULL,
    base_url          VARCHAR(500) NOT NULL,
    auth_type         VARCHAR(30) NOT NULL,
    auth_config       JSONB NOT NULL DEFAULT '{}'::JSONB,
    supported_types   JSONB NULL,
    remark            VARCHAR(255) NULL,
    sync_status       VARCHAR(20) NOT NULL DEFAULT 'pending',
    last_sync_at      TIMESTAMPTZ NULL,
    last_sync_error   VARCHAR(500) NULL,
    created_by        BIGINT NULL,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uk_ai_model_provider_enterprise_name_url UNIQUE (enterprise_id, provider_name, base_url),
    CONSTRAINT uk_ai_model_provider_enterprise_id UNIQUE (enterprise_id, id),
    CONSTRAINT ck_ai_model_provider_deployment_type CHECK (deployment_type IN ('public', 'private')),
    CONSTRAINT ck_ai_model_provider_auth_type CHECK (auth_type IN ('api_key', 'bearer', 'basic', 'custom')),
    CONSTRAINT ck_ai_model_provider_sync_status CHECK (sync_status IN ('pending', 'success', 'failed')),
    CONSTRAINT ck_ai_model_provider_auth_config CHECK (jsonb_typeof(auth_config) = 'object'),
    CONSTRAINT ck_ai_model_provider_supported_types CHECK (
        supported_types IS NULL OR jsonb_typeof(supported_types) = 'array'
    ),
    CONSTRAINT fk_ai_model_provider_enterprise FOREIGN KEY (enterprise_id)
        REFERENCES public.enterprise_space(id)
        ON DELETE CASCADE
);

COMMENT ON TABLE public.ai_model_provider IS '企业空间下已接入的模型厂商配置表';
COMMENT ON COLUMN public.ai_model_provider.id IS '主键ID';
COMMENT ON COLUMN public.ai_model_provider.enterprise_id IS '企业空间ID';
COMMENT ON COLUMN public.ai_model_provider.provider_code IS '厂商编码，如 openai/deepseek/qwen/custom';
COMMENT ON COLUMN public.ai_model_provider.provider_name IS '厂商显示名称';
COMMENT ON COLUMN public.ai_model_provider.deployment_type IS '部署类型：public/private';
COMMENT ON COLUMN public.ai_model_provider.base_url IS '模型服务基础地址';
COMMENT ON COLUMN public.ai_model_provider.auth_type IS '认证类型：api_key/bearer/basic/custom';
COMMENT ON COLUMN public.ai_model_provider.auth_config IS '认证配置，建议存加密后的 JSON';
COMMENT ON COLUMN public.ai_model_provider.supported_types IS '支持的模型类型列表，如 ["llm","embedding","rerank"]';
COMMENT ON COLUMN public.ai_model_provider.remark IS '备注';
COMMENT ON COLUMN public.ai_model_provider.sync_status IS '同步状态：pending/success/failed';
COMMENT ON COLUMN public.ai_model_provider.last_sync_at IS '最近同步模型时间';
COMMENT ON COLUMN public.ai_model_provider.last_sync_error IS '最近同步错误信息';
COMMENT ON COLUMN public.ai_model_provider.created_by IS '创建人';
COMMENT ON COLUMN public.ai_model_provider.created_at IS '创建时间';
COMMENT ON COLUMN public.ai_model_provider.updated_at IS '更新时间';

CREATE INDEX IF NOT EXISTS idx_ai_model_provider_enterprise_id
    ON public.ai_model_provider (enterprise_id);
CREATE INDEX IF NOT EXISTS idx_ai_model_provider_code
    ON public.ai_model_provider (provider_code);
CREATE INDEX IF NOT EXISTS idx_ai_model_provider_deployment_type
    ON public.ai_model_provider (deployment_type);
CREATE INDEX IF NOT EXISTS idx_ai_model_provider_sync_status
    ON public.ai_model_provider (sync_status);

DROP TRIGGER IF EXISTS trg_ai_model_provider_set_updated_at ON public.ai_model_provider;
CREATE TRIGGER trg_ai_model_provider_set_updated_at
BEFORE UPDATE ON public.ai_model_provider
FOR EACH ROW
EXECUTE FUNCTION public.fn_set_updated_at();

-- =========================
-- 4. 模型表
-- =========================
CREATE TABLE IF NOT EXISTS public.ai_model (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enterprise_id     BIGINT NOT NULL,
    provider_id       BIGINT NOT NULL,
    model_code        VARCHAR(150) NOT NULL,
    model_name        VARCHAR(150) NOT NULL,
    model_type        VARCHAR(30) NOT NULL,
    is_enabled        BOOLEAN NOT NULL DEFAULT FALSE,
    context_window    INTEGER NULL,
    max_output_tokens INTEGER NULL,
    capabilities      JSONB NULL,
    raw_payload       JSONB NULL,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uk_ai_model_provider_model_code UNIQUE (provider_id, model_code),
    CONSTRAINT uk_ai_model_enterprise_id UNIQUE (enterprise_id, id),
    CONSTRAINT uk_ai_model_enterprise_type_id UNIQUE (enterprise_id, model_type, id),
    CONSTRAINT ck_ai_model_type CHECK (model_type IN ('llm', 'embedding', 'rerank', 'tts', 'asr', 'vlm', 'moderation', 'ocr')),
    CONSTRAINT ck_ai_model_context_window CHECK (context_window IS NULL OR context_window > 0),
    CONSTRAINT ck_ai_model_max_output_tokens CHECK (max_output_tokens IS NULL OR max_output_tokens > 0),
    CONSTRAINT ck_ai_model_capabilities CHECK (
        capabilities IS NULL OR jsonb_typeof(capabilities) = 'array'
    ),
    CONSTRAINT fk_ai_model_enterprise FOREIGN KEY (enterprise_id)
        REFERENCES public.enterprise_space(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_ai_model_provider FOREIGN KEY (enterprise_id, provider_id)
        REFERENCES public.ai_model_provider(enterprise_id, id)
        ON DELETE CASCADE
);

COMMENT ON TABLE public.ai_model IS '企业空间下可用模型表';
COMMENT ON COLUMN public.ai_model.id IS '主键ID';
COMMENT ON COLUMN public.ai_model.enterprise_id IS '企业空间ID';
COMMENT ON COLUMN public.ai_model.provider_id IS '所属厂商配置ID';
COMMENT ON COLUMN public.ai_model.model_code IS '模型编码，如 gpt-4o';
COMMENT ON COLUMN public.ai_model.model_name IS '模型名称';
COMMENT ON COLUMN public.ai_model.model_type IS '模型类型：llm/embedding/rerank/tts/asr/vlm/moderation/ocr';
COMMENT ON COLUMN public.ai_model.is_enabled IS '是否启用，true 启用后才允许调用';
COMMENT ON COLUMN public.ai_model.context_window IS '上下文长度';
COMMENT ON COLUMN public.ai_model.max_output_tokens IS '最大输出 token';
COMMENT ON COLUMN public.ai_model.capabilities IS '能力标签列表，如 ["vision","function_call"]';
COMMENT ON COLUMN public.ai_model.raw_payload IS '供应商原始返回 JSON';
COMMENT ON COLUMN public.ai_model.created_at IS '创建时间';
COMMENT ON COLUMN public.ai_model.updated_at IS '更新时间';

CREATE INDEX IF NOT EXISTS idx_ai_model_enterprise_type_enabled
    ON public.ai_model (enterprise_id, model_type, is_enabled);
CREATE INDEX IF NOT EXISTS idx_ai_model_provider_id
    ON public.ai_model (provider_id);
CREATE INDEX IF NOT EXISTS idx_ai_model_enterprise_model_name
    ON public.ai_model (enterprise_id, model_name);

DROP TRIGGER IF EXISTS trg_ai_model_set_updated_at ON public.ai_model;
CREATE TRIGGER trg_ai_model_set_updated_at
BEFORE UPDATE ON public.ai_model
FOR EACH ROW
EXECUTE FUNCTION public.fn_set_updated_at();

-- =========================
-- 5. 默认模型表
-- =========================
CREATE TABLE IF NOT EXISTS public.ai_model_default (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enterprise_id BIGINT NOT NULL,
    model_type    VARCHAR(30) NOT NULL,
    model_id      BIGINT NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uk_ai_model_default_enterprise_type UNIQUE (enterprise_id, model_type),
    CONSTRAINT ck_ai_model_default_type CHECK (model_type IN ('llm', 'embedding', 'rerank', 'tts', 'asr', 'vlm', 'moderation', 'ocr')),
    CONSTRAINT fk_ai_model_default_enterprise FOREIGN KEY (enterprise_id)
        REFERENCES public.enterprise_space(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_ai_model_default_model FOREIGN KEY (enterprise_id, model_type, model_id)
        REFERENCES public.ai_model(enterprise_id, model_type, id)
        ON DELETE RESTRICT
);

COMMENT ON TABLE public.ai_model_default IS '企业空间默认模型表';
COMMENT ON COLUMN public.ai_model_default.id IS '主键ID';
COMMENT ON COLUMN public.ai_model_default.enterprise_id IS '企业空间ID';
COMMENT ON COLUMN public.ai_model_default.model_type IS '模型类型';
COMMENT ON COLUMN public.ai_model_default.model_id IS '默认模型ID，必须是已启用模型';
COMMENT ON COLUMN public.ai_model_default.created_at IS '创建时间';
COMMENT ON COLUMN public.ai_model_default.updated_at IS '更新时间';

CREATE INDEX IF NOT EXISTS idx_ai_model_default_model_id
    ON public.ai_model_default (model_id);

DROP TRIGGER IF EXISTS trg_ai_model_default_set_updated_at ON public.ai_model_default;
CREATE TRIGGER trg_ai_model_default_set_updated_at
BEFORE UPDATE ON public.ai_model_default
FOR EACH ROW
EXECUTE FUNCTION public.fn_set_updated_at();

-- =========================
-- 6. 默认模型校验：必须为已启用模型
-- =========================
CREATE OR REPLACE FUNCTION public.fn_validate_ai_model_default_enabled()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM public.ai_model m
        WHERE m.id = NEW.model_id
          AND m.enterprise_id = NEW.enterprise_id
          AND m.model_type = NEW.model_type
          AND m.is_enabled = TRUE
    ) THEN
        RAISE EXCEPTION '默认模型必须是当前企业空间下已启用且类型匹配的模型';
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_validate_ai_model_default_enabled ON public.ai_model_default;
CREATE TRIGGER trg_validate_ai_model_default_enabled
BEFORE INSERT OR UPDATE ON public.ai_model_default
FOR EACH ROW
EXECUTE FUNCTION public.fn_validate_ai_model_default_enabled();

-- =========================
-- 7. 防止禁用已被设为默认的模型
-- =========================
CREATE OR REPLACE FUNCTION public.fn_prevent_disable_default_model()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF OLD.is_enabled = TRUE
       AND NEW.is_enabled = FALSE
       AND EXISTS (
           SELECT 1
           FROM public.ai_model_default d
           WHERE d.enterprise_id = OLD.enterprise_id
             AND d.model_type = OLD.model_type
             AND d.model_id = OLD.id
       ) THEN
        RAISE EXCEPTION '该模型已被设为默认模型，请先调整默认模型后再禁用';
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_prevent_disable_default_model ON public.ai_model;
CREATE TRIGGER trg_prevent_disable_default_model
BEFORE UPDATE OF is_enabled ON public.ai_model
FOR EACH ROW
EXECUTE FUNCTION public.fn_prevent_disable_default_model();

COMMIT;

-- =========================
-- 8. 查询建议
-- =========================
-- 8.1 查询企业空间默认模型
-- SELECT d.model_type, m.model_name, p.provider_name
-- FROM public.ai_model_default d
-- JOIN public.ai_model m ON m.id = d.model_id
-- JOIN public.ai_model_provider p ON p.id = m.provider_id
-- WHERE d.enterprise_id = :enterprise_id;

-- 8.2 查询已添加厂商及其模型
-- SELECT p.id AS provider_id, p.provider_name, p.provider_code, p.deployment_type,
--        m.id AS model_id, m.model_name, m.model_code, m.model_type, m.is_enabled
-- FROM public.ai_model_provider p
-- LEFT JOIN public.ai_model m ON m.provider_id = p.id
-- WHERE p.enterprise_id = :enterprise_id
-- ORDER BY p.created_at DESC, m.model_type, m.model_name;
