"""Add chat tables

Revision ID: 052433bd5878
Revises: 8eba9eab2dc9
Create Date: 2026-04-27 15:54:49.264595
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '052433bd5878'
down_revision = '8eba9eab2dc9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
