"""Add chat tables

Revision ID: 8eba9eab2dc9
Revises: 013_kb_default_chunk_512_50
Create Date: 2026-04-27 15:52:42.818383
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8eba9eab2dc9'
down_revision = '013_kb_default_chunk_512_50'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_session',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('enterprise_space_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_space_id'], ['enterprise_space.id'], name=op.f('fk_chat_session_enterprise_space_id_enterprise_space'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_chat_session_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_session'))
    )
    op.create_index(op.f('ix_chat_session_enterprise_space_id'), 'chat_session', ['enterprise_space_id'], unique=False)
    op.create_index(op.f('ix_chat_session_user_id'), 'chat_session', ['user_id'], unique=False)
    op.create_table('chat_configuration',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('model_provider', sa.String(length=100), nullable=True),
    sa.Column('model_name', sa.String(length=150), nullable=True),
    sa.Column('knowledge_base_ids', sa.JSON(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('top_p', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_session.id'], name=op.f('fk_chat_configuration_session_id_chat_session'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_configuration')),
    sa.UniqueConstraint('session_id', name=op.f('uq_chat_configuration_session_id'))
    )
    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_session.id'], name=op.f('fk_chat_message_session_id_chat_session'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_message'))
    )
    op.create_index(op.f('ix_chat_message_session_id'), 'chat_message', ['session_id'], unique=False)
    op.alter_column('ai_model', 'capabilities',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('ai_model_provider', 'remark',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_constraint('uq_enterprise_space_name', 'enterprise_space', type_='unique')
    op.drop_constraint('uq_enterprise_space_slug', 'enterprise_space', type_='unique')
    op.drop_index('ix_enterprise_space_name', table_name='enterprise_space')
    op.create_index(op.f('ix_enterprise_space_name'), 'enterprise_space', ['name'], unique=True)
    op.drop_index('ix_enterprise_space_slug', table_name='enterprise_space')
    op.create_index(op.f('ix_enterprise_space_slug'), 'enterprise_space', ['slug'], unique=True)
    op.drop_index('idx_knowledge_base_space_status', table_name='knowledge_base')
    op.drop_index('gin_chunk_search_vector', table_name='knowledge_chunk', postgresql_using='gin')
    op.drop_index('idx_chunk_kb_document', table_name='knowledge_chunk')
    op.drop_index('idx_chunk_kb_vector_status', table_name='knowledge_chunk')
    op.alter_column('knowledge_document', 'file_size',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_index('idx_document_kb_created_at', table_name='knowledge_document')
    op.drop_index('idx_document_space_kb_status', table_name='knowledge_document')
    op.drop_index('ix_neo4j_connection_knowledge_base_id', table_name='neo4j_connection')
    op.create_index(op.f('ix_neo4j_connection_knowledge_base_id'), 'neo4j_connection', ['knowledge_base_id'], unique=True)
    op.drop_constraint('uq_user_email', 'user', type_='unique')
    op.drop_constraint('uq_user_username', 'user', type_='unique')
    op.drop_index('ix_user_email', table_name='user')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.drop_index('ix_user_username', table_name='user')
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.create_index('ix_user_username', 'user', ['username'], unique=False)
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    op.create_unique_constraint('uq_user_username', 'user', ['username'])
    op.create_unique_constraint('uq_user_email', 'user', ['email'])
    op.drop_index(op.f('ix_neo4j_connection_knowledge_base_id'), table_name='neo4j_connection')
    op.create_index('ix_neo4j_connection_knowledge_base_id', 'neo4j_connection', ['knowledge_base_id'], unique=False)
    op.create_index('idx_document_space_kb_status', 'knowledge_document', ['enterprise_space_id', 'knowledge_base_id', 'status'], unique=False)
    op.create_index('idx_document_kb_created_at', 'knowledge_document', ['knowledge_base_id', 'created_at'], unique=False)
    op.alter_column('knowledge_document', 'file_size',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.create_index('idx_chunk_kb_vector_status', 'knowledge_chunk', ['knowledge_base_id', 'vector_status'], unique=False)
    op.create_index('idx_chunk_kb_document', 'knowledge_chunk', ['knowledge_base_id', 'document_id'], unique=False)
    op.create_index('gin_chunk_search_vector', 'knowledge_chunk', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('idx_knowledge_base_space_status', 'knowledge_base', ['enterprise_space_id', 'status'], unique=False)
    op.drop_index(op.f('ix_enterprise_space_slug'), table_name='enterprise_space')
    op.create_index('ix_enterprise_space_slug', 'enterprise_space', ['slug'], unique=False)
    op.drop_index(op.f('ix_enterprise_space_name'), table_name='enterprise_space')
    op.create_index('ix_enterprise_space_name', 'enterprise_space', ['name'], unique=False)
    op.create_unique_constraint('uq_enterprise_space_slug', 'enterprise_space', ['slug'])
    op.create_unique_constraint('uq_enterprise_space_name', 'enterprise_space', ['name'])
    op.alter_column('ai_model_provider', 'remark',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('ai_model', 'capabilities',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_index(op.f('ix_chat_message_session_id'), table_name='chat_message')
    op.drop_table('chat_message')
    op.drop_table('chat_configuration')
    op.drop_index(op.f('ix_chat_session_user_id'), table_name='chat_session')
    op.drop_index(op.f('ix_chat_session_enterprise_space_id'), table_name='chat_session')
    op.drop_table('chat_session')
    # ### end Alembic commands ###
